// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onlinejudge.proto

#include "onlinejudge.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_onlinejudge_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_onlinejudge_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_qName;
}  // namespace protobuf_onlinejudge_2eproto
namespace onlinejudge {
class qNameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<qName>
      _instance;
} _qName_default_instance_;
class qUestionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<qUestion>
      _instance;
} _qUestion_default_instance_;
class qSubmitDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<qSubmit>
      _instance;
} _qSubmit_default_instance_;
class replyResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<replyResult>
      _instance;
} _replyResult_default_instance_;
}  // namespace onlinejudge
namespace protobuf_onlinejudge_2eproto {
static void InitDefaultsqName() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::onlinejudge::_qName_default_instance_;
    new (ptr) ::onlinejudge::qName();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::onlinejudge::qName::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_qName =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsqName}, {}};

static void InitDefaultsqUestion() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::onlinejudge::_qUestion_default_instance_;
    new (ptr) ::onlinejudge::qUestion();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::onlinejudge::qUestion::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_qUestion =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsqUestion}, {
      &protobuf_onlinejudge_2eproto::scc_info_qName.base,}};

static void InitDefaultsqSubmit() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::onlinejudge::_qSubmit_default_instance_;
    new (ptr) ::onlinejudge::qSubmit();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::onlinejudge::qSubmit::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_qSubmit =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsqSubmit}, {
      &protobuf_onlinejudge_2eproto::scc_info_qName.base,}};

static void InitDefaultsreplyResult() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::onlinejudge::_replyResult_default_instance_;
    new (ptr) ::onlinejudge::replyResult();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::onlinejudge::replyResult::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_replyResult =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsreplyResult}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_qName.base);
  ::google::protobuf::internal::InitSCC(&scc_info_qUestion.base);
  ::google::protobuf::internal::InitSCC(&scc_info_qSubmit.base);
  ::google::protobuf::internal::InitSCC(&scc_info_replyResult.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qName, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qName, keyname_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qUestion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qUestion, n_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qUestion, message_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qSubmit, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qSubmit, n_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::qSubmit, qsubmitcode_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::replyResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::onlinejudge::replyResult, message_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::onlinejudge::qName)},
  { 6, -1, sizeof(::onlinejudge::qUestion)},
  { 13, -1, sizeof(::onlinejudge::qSubmit)},
  { 20, -1, sizeof(::onlinejudge::replyResult)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::onlinejudge::_qName_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::onlinejudge::_qUestion_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::onlinejudge::_qSubmit_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::onlinejudge::_replyResult_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "onlinejudge.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021onlinejudge.proto\022\013onlinejudge\"\030\n\005qNam"
      "e\022\017\n\007keyname\030\001 \001(\t\":\n\010qUestion\022\035\n\001N\030\001 \001("
      "\0132\022.onlinejudge.qName\022\017\n\007message\030\002 \001(\t\"="
      "\n\007qSubmit\022\035\n\001N\030\001 \001(\0132\022.onlinejudge.qName"
      "\022\023\n\013qSubmitCode\030\002 \001(\t\"\036\n\013replyResult\022\017\n\007"
      "message\030\001 \001(\t2\367\001\n\013OnlineJudge\0228\n\010listQue"
      "s\022\024.onlinejudge.qSubmit\032\022.onlinejudge.qN"
      "ame\"\0000\001\0229\n\ndetailQues\022\022.onlinejudge.qNam"
      "e\032\025.onlinejudge.qUestion\"\000\0229\n\005jUdge\022\024.on"
      "linejudge.qSubmit\032\030.onlinejudge.replyRes"
      "ult\"\000\0228\n\006rEsult\022\022.onlinejudge.qName\032\030.on"
      "linejudge.replyResult\"\000B8\n\034io.grpc.examp"
      "les.onlinejudgeB\020OnlineJudgeProtoP\001\242\002\003OJ"
      "Pb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 529);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "onlinejudge.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_onlinejudge_2eproto
namespace onlinejudge {

// ===================================================================

void qName::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int qName::kKeynameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

qName::qName()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onlinejudge_2eproto::scc_info_qName.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onlinejudge.qName)
}
qName::qName(const qName& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  keyname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.keyname().size() > 0) {
    keyname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.keyname_);
  }
  // @@protoc_insertion_point(copy_constructor:onlinejudge.qName)
}

void qName::SharedCtor() {
  keyname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

qName::~qName() {
  // @@protoc_insertion_point(destructor:onlinejudge.qName)
  SharedDtor();
}

void qName::SharedDtor() {
  keyname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void qName::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* qName::descriptor() {
  ::protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const qName& qName::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onlinejudge_2eproto::scc_info_qName.base);
  return *internal_default_instance();
}


void qName::Clear() {
// @@protoc_insertion_point(message_clear_start:onlinejudge.qName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  keyname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool qName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:onlinejudge.qName)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string keyname = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_keyname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->keyname().data(), static_cast<int>(this->keyname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "onlinejudge.qName.keyname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onlinejudge.qName)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onlinejudge.qName)
  return false;
#undef DO_
}

void qName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onlinejudge.qName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string keyname = 1;
  if (this->keyname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->keyname().data(), static_cast<int>(this->keyname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.qName.keyname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->keyname(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:onlinejudge.qName)
}

::google::protobuf::uint8* qName::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:onlinejudge.qName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string keyname = 1;
  if (this->keyname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->keyname().data(), static_cast<int>(this->keyname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.qName.keyname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->keyname(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onlinejudge.qName)
  return target;
}

size_t qName::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onlinejudge.qName)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string keyname = 1;
  if (this->keyname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->keyname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void qName::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:onlinejudge.qName)
  GOOGLE_DCHECK_NE(&from, this);
  const qName* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const qName>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:onlinejudge.qName)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:onlinejudge.qName)
    MergeFrom(*source);
  }
}

void qName::MergeFrom(const qName& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onlinejudge.qName)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.keyname().size() > 0) {

    keyname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.keyname_);
  }
}

void qName::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:onlinejudge.qName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void qName::CopyFrom(const qName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onlinejudge.qName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool qName::IsInitialized() const {
  return true;
}

void qName::Swap(qName* other) {
  if (other == this) return;
  InternalSwap(other);
}
void qName::InternalSwap(qName* other) {
  using std::swap;
  keyname_.Swap(&other->keyname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata qName::GetMetadata() const {
  protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void qUestion::InitAsDefaultInstance() {
  ::onlinejudge::_qUestion_default_instance_._instance.get_mutable()->n_ = const_cast< ::onlinejudge::qName*>(
      ::onlinejudge::qName::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int qUestion::kNFieldNumber;
const int qUestion::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

qUestion::qUestion()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onlinejudge_2eproto::scc_info_qUestion.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onlinejudge.qUestion)
}
qUestion::qUestion(const qUestion& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.has_n()) {
    n_ = new ::onlinejudge::qName(*from.n_);
  } else {
    n_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:onlinejudge.qUestion)
}

void qUestion::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  n_ = NULL;
}

qUestion::~qUestion() {
  // @@protoc_insertion_point(destructor:onlinejudge.qUestion)
  SharedDtor();
}

void qUestion::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete n_;
}

void qUestion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* qUestion::descriptor() {
  ::protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const qUestion& qUestion::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onlinejudge_2eproto::scc_info_qUestion.base);
  return *internal_default_instance();
}


void qUestion::Clear() {
// @@protoc_insertion_point(message_clear_start:onlinejudge.qUestion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && n_ != NULL) {
    delete n_;
  }
  n_ = NULL;
  _internal_metadata_.Clear();
}

bool qUestion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:onlinejudge.qUestion)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .onlinejudge.qName N = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_n()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "onlinejudge.qUestion.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onlinejudge.qUestion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onlinejudge.qUestion)
  return false;
#undef DO_
}

void qUestion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onlinejudge.qUestion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .onlinejudge.qName N = 1;
  if (this->has_n()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_n(), output);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.qUestion.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:onlinejudge.qUestion)
}

::google::protobuf::uint8* qUestion::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:onlinejudge.qUestion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .onlinejudge.qName N = 1;
  if (this->has_n()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_n(), deterministic, target);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.qUestion.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onlinejudge.qUestion)
  return target;
}

size_t qUestion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onlinejudge.qUestion)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // .onlinejudge.qName N = 1;
  if (this->has_n()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *n_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void qUestion::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:onlinejudge.qUestion)
  GOOGLE_DCHECK_NE(&from, this);
  const qUestion* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const qUestion>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:onlinejudge.qUestion)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:onlinejudge.qUestion)
    MergeFrom(*source);
  }
}

void qUestion::MergeFrom(const qUestion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onlinejudge.qUestion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.has_n()) {
    mutable_n()->::onlinejudge::qName::MergeFrom(from.n());
  }
}

void qUestion::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:onlinejudge.qUestion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void qUestion::CopyFrom(const qUestion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onlinejudge.qUestion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool qUestion::IsInitialized() const {
  return true;
}

void qUestion::Swap(qUestion* other) {
  if (other == this) return;
  InternalSwap(other);
}
void qUestion::InternalSwap(qUestion* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(n_, other->n_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata qUestion::GetMetadata() const {
  protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void qSubmit::InitAsDefaultInstance() {
  ::onlinejudge::_qSubmit_default_instance_._instance.get_mutable()->n_ = const_cast< ::onlinejudge::qName*>(
      ::onlinejudge::qName::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int qSubmit::kNFieldNumber;
const int qSubmit::kQSubmitCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

qSubmit::qSubmit()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onlinejudge_2eproto::scc_info_qSubmit.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onlinejudge.qSubmit)
}
qSubmit::qSubmit(const qSubmit& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  qsubmitcode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.qsubmitcode().size() > 0) {
    qsubmitcode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qsubmitcode_);
  }
  if (from.has_n()) {
    n_ = new ::onlinejudge::qName(*from.n_);
  } else {
    n_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:onlinejudge.qSubmit)
}

void qSubmit::SharedCtor() {
  qsubmitcode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  n_ = NULL;
}

qSubmit::~qSubmit() {
  // @@protoc_insertion_point(destructor:onlinejudge.qSubmit)
  SharedDtor();
}

void qSubmit::SharedDtor() {
  qsubmitcode_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete n_;
}

void qSubmit::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* qSubmit::descriptor() {
  ::protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const qSubmit& qSubmit::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onlinejudge_2eproto::scc_info_qSubmit.base);
  return *internal_default_instance();
}


void qSubmit::Clear() {
// @@protoc_insertion_point(message_clear_start:onlinejudge.qSubmit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  qsubmitcode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && n_ != NULL) {
    delete n_;
  }
  n_ = NULL;
  _internal_metadata_.Clear();
}

bool qSubmit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:onlinejudge.qSubmit)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .onlinejudge.qName N = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_n()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string qSubmitCode = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_qsubmitcode()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->qsubmitcode().data(), static_cast<int>(this->qsubmitcode().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "onlinejudge.qSubmit.qSubmitCode"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onlinejudge.qSubmit)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onlinejudge.qSubmit)
  return false;
#undef DO_
}

void qSubmit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onlinejudge.qSubmit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .onlinejudge.qName N = 1;
  if (this->has_n()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_n(), output);
  }

  // string qSubmitCode = 2;
  if (this->qsubmitcode().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qsubmitcode().data(), static_cast<int>(this->qsubmitcode().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.qSubmit.qSubmitCode");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->qsubmitcode(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:onlinejudge.qSubmit)
}

::google::protobuf::uint8* qSubmit::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:onlinejudge.qSubmit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .onlinejudge.qName N = 1;
  if (this->has_n()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_n(), deterministic, target);
  }

  // string qSubmitCode = 2;
  if (this->qsubmitcode().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qsubmitcode().data(), static_cast<int>(this->qsubmitcode().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.qSubmit.qSubmitCode");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->qsubmitcode(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onlinejudge.qSubmit)
  return target;
}

size_t qSubmit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onlinejudge.qSubmit)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string qSubmitCode = 2;
  if (this->qsubmitcode().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->qsubmitcode());
  }

  // .onlinejudge.qName N = 1;
  if (this->has_n()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *n_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void qSubmit::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:onlinejudge.qSubmit)
  GOOGLE_DCHECK_NE(&from, this);
  const qSubmit* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const qSubmit>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:onlinejudge.qSubmit)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:onlinejudge.qSubmit)
    MergeFrom(*source);
  }
}

void qSubmit::MergeFrom(const qSubmit& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onlinejudge.qSubmit)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.qsubmitcode().size() > 0) {

    qsubmitcode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qsubmitcode_);
  }
  if (from.has_n()) {
    mutable_n()->::onlinejudge::qName::MergeFrom(from.n());
  }
}

void qSubmit::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:onlinejudge.qSubmit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void qSubmit::CopyFrom(const qSubmit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onlinejudge.qSubmit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool qSubmit::IsInitialized() const {
  return true;
}

void qSubmit::Swap(qSubmit* other) {
  if (other == this) return;
  InternalSwap(other);
}
void qSubmit::InternalSwap(qSubmit* other) {
  using std::swap;
  qsubmitcode_.Swap(&other->qsubmitcode_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(n_, other->n_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata qSubmit::GetMetadata() const {
  protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void replyResult::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int replyResult::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

replyResult::replyResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onlinejudge_2eproto::scc_info_replyResult.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onlinejudge.replyResult)
}
replyResult::replyResult(const replyResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:onlinejudge.replyResult)
}

void replyResult::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

replyResult::~replyResult() {
  // @@protoc_insertion_point(destructor:onlinejudge.replyResult)
  SharedDtor();
}

void replyResult::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void replyResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* replyResult::descriptor() {
  ::protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const replyResult& replyResult::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onlinejudge_2eproto::scc_info_replyResult.base);
  return *internal_default_instance();
}


void replyResult::Clear() {
// @@protoc_insertion_point(message_clear_start:onlinejudge.replyResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool replyResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:onlinejudge.replyResult)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "onlinejudge.replyResult.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onlinejudge.replyResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onlinejudge.replyResult)
  return false;
#undef DO_
}

void replyResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onlinejudge.replyResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.replyResult.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:onlinejudge.replyResult)
}

::google::protobuf::uint8* replyResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:onlinejudge.replyResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "onlinejudge.replyResult.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onlinejudge.replyResult)
  return target;
}

size_t replyResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onlinejudge.replyResult)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void replyResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:onlinejudge.replyResult)
  GOOGLE_DCHECK_NE(&from, this);
  const replyResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const replyResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:onlinejudge.replyResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:onlinejudge.replyResult)
    MergeFrom(*source);
  }
}

void replyResult::MergeFrom(const replyResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onlinejudge.replyResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void replyResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:onlinejudge.replyResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void replyResult::CopyFrom(const replyResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onlinejudge.replyResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool replyResult::IsInitialized() const {
  return true;
}

void replyResult::Swap(replyResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void replyResult::InternalSwap(replyResult* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata replyResult::GetMetadata() const {
  protobuf_onlinejudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_onlinejudge_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace onlinejudge
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onlinejudge::qName* Arena::CreateMaybeMessage< ::onlinejudge::qName >(Arena* arena) {
  return Arena::CreateInternal< ::onlinejudge::qName >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onlinejudge::qUestion* Arena::CreateMaybeMessage< ::onlinejudge::qUestion >(Arena* arena) {
  return Arena::CreateInternal< ::onlinejudge::qUestion >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onlinejudge::qSubmit* Arena::CreateMaybeMessage< ::onlinejudge::qSubmit >(Arena* arena) {
  return Arena::CreateInternal< ::onlinejudge::qSubmit >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onlinejudge::replyResult* Arena::CreateMaybeMessage< ::onlinejudge::replyResult >(Arena* arena) {
  return Arena::CreateInternal< ::onlinejudge::replyResult >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
